# West manifest for Xi 640 ETH Thermal Camera
# Zephyr main branch (includes STM32N6570-DK support)
manifest:
  version: "0.13"

  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true

  self:
    path: xi640-base
